services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
  kafka:
    container_name: kafka
    image: apache/kafka
    ports:
      - "9092:9092"